FROM golang:1.16.2

RUN go get github.com/canthefason/go-watcher
RUN go install github.com/canthefason/go-watcher/cmd/watcher@latest

ADD . /go/src/github.com/ebalkanski/grpc/
RUN cd /go/src/github.com/ebalkanski/grpc/ && go install github.com/ebalkanski/grpc/cmd/server/...

WORKDIR /go/src/github.com/ebalkanski/grpc/
EXPOSE 8081

ENTRYPOINT ["sh", "-c", "/go/bin/watcher -run github.com/ebalkanski/grpc/cmd/server -watch github.com/ebalkanski/grpc"]